name: Trigger Weekly Pipeline

on:
  schedule:
    - cron: '0 13 * * 2'   # Tuesday 13:00 UTC
    - cron: '0 16 * * 5'   # Friday 16:00 UTC
  workflow_dispatch:       # allow manual runs from Actions tab

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel endpoint
        env:
          URL: ${{ secrets.VERCEL_TRIGGER_URL }}   # e.g. https://your-app.vercel.app/api/trigger-weekly
          TOKEN: ${{ secrets.TRIGGER_TOKEN }}      # same as your Vercel TRIGGER_TOKEN
        run: |
          set -e
          if [ -z "$URL" ] || [ -z "$TOKEN" ]; then
            echo "Missing secrets VERCEL_TRIGGER_URL or TRIGGER_TOKEN"
            exit 1
          fi

          # Hit the Vercel endpoint with the secret header
          http_code=$(curl -s -o /tmp/resp.json -w "%{http_code}" \
            -X POST "$URL" \
            -H "x-trigger-token: $TOKEN" \
            -H "content-type: application/json" \
            --data '{}')

          echo "HTTP $http_code"
          cat /tmp/resp.json

          # Fail the job if HTTP code is not 2xx
          if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
            exit 1
          fi
